name: 'rhub-setup'
description: |
  Setup platform matrices to run R-hub jobs.
author: 'Gábor Csárdi'

inputs:
  config:
    description: |
      R-hub configuration. A JSON string, see documentation for details.

outputs:
  containers:
    description: 'Container platforms.'
    value: ${{ steps.config.outputs.containers }}
  platforms:
    description: 'Other R-hub platforms.'
    value: ${{ steps.config.outputs.platforms }}

runs:
  using: "composite"
  steps:
  - name: Configure R-hub platforms
    id: config
    run: |
        containers='[{"name": "clang16", "container": "ghcr.io/r-hub/containers/clang16:latest"}, {"name": "gcc13", "container": "ghcr.io/r-hub/containers/gcc13:latest"}]'
        echo "containers=$containers" >> $GITHUB_OUTPUT
        platforms='[{"os": "macos-latest","r": "release"},{"os":"windows-latest","r": "release"}]'
        echo "platforms=$platforms" >> $GITHUB_OUTPUT
    shell: bash
