name: 'rhub-setup-r'
description: |
  Install and setup R for R-hub jobs.
author: 'Gábor Csárdi'

inputs:
  config:
    description: |
      R-hub configuration. A JSON string, see documentation for details.
  platform:
    description: |
      The matrix config, as set up by the r-hub-setup action.

  token:
    description: |
      Custom GitHub personal access token. Useful to allow access to
      private repositories or other resources.

runs:
  using: "composite"
  steps:
  - uses: r-lib/actions/setup-r@v2
    with:
      r-version: ${{ fromJSON('${{ github.event.inputs.platform}}').r-version }}
      use-public-rspm: true
