name: 'rhub-check'
description: |
  Run R-hub checks.
author: 'Gábor Csárdi'

inputs:
  token:
    description: |
      Custom GitHub personal access token. Useful to allow access to
      private repositories or other resources.
  job-config:
    description: |
      The matrix config, as set up by the r-hub-setup action.

runs:
  using: "composite"
  steps:
  - name: Environment variables
    run: |
      Sys.getenv()
    shell: Rscript {0}

  - name: OS information
    run: |
      if (Sys.info()[["sysname"]] == "Linux") {
        system("uname -a")
        if (file.exists("/etc/os-release")) {
          writeLines(readLines("/etc/os-release"))
        }
      }
    shell: Rscript {0}

  - name: R infomation
    run: |
      sessionInfo()
      capabilities()
      extSoftVersion()
      l10n_info()
    shell: Rscript {0}

  - name: Set user library location
    run: |
      # Set user library location for setup-r-dependencies caching
      dir.create(lib <- Sys.getenv("R_LIBS_USER"), showWarnings = FALSE, recursive = TRUE)
      writeLines(paste0("R_LIBS_USER=", Sys.getenv("R_LIBS_USER")), Sys.getenv("GITHUB_ENV"))
    shell: Rscript {0}

  # TODO: need to improve the cache key for R builds/packages that
  # - link to libc++ on Linux
  # - don't have an R shared library
  - uses: r-lib/actions/setup-r-dependencies@v2-branch
    with:
      extra-packages: any::rcmdcheck
      needs: check
    env:
      R_KEEP_PKG_SOURCE: yes

  - uses: r-lib/actions/check-r-package@v2
    with:
      upload-snapshots: true
    env:
      R_KEEP_PKG_SOURCE: yes
