name: 'rhub-check'
description: |
  Run R-hub checks.
author: 'Gábor Csárdi'

inputs:
  config:
    description: |
      R-hub configuration. A JSON string, see documentation for details.

runs:
  using: "composite"
  steps:
  - name: Session info
    run: |
      sessionInfo()
    shell: Rscript {0}

  # TODO: fix caching, R_LIBS_USER is not set in Docker, only if setup-r runs
  - uses: r-lib/actions/setup-r-dependencies@v2-branch
    with:
      extra-packages: any::rcmdcheck
      needs: check
      cache: false
    env:
      R_KEEP_PKG_SOURCE: yes

  - uses: r-lib/actions/check-r-package@v2
    with:
      upload-snapshots: true
    env:
      R_KEEP_PKG_SOURCE: yes
