name: 'rhub-check'
description: |
  Run R-hub checks.
author: 'Gábor Csárdi'

inputs:
  config:
    description: |
      R-hub configuration. A JSON string, see documentation for details.

runs:
  using: "composite"
  steps:
  - name: Session info
    run: |
      sessionInfo()
    shell: Rscript {0}

  - name: Set user library location
  - run: |
      dir.create(lib <- Sys.getenv("R_LIBS_USER"), showWarnings = FALSE, recursive = TRUE)
      writeLines(paste0("R_LIBS_USER=", Sys.getenv("R_LIBS_USER"))
    shell: Rscript {0}

  # TODO: need to improve the cache key for R builds/packages that
  # - link to libc++ on Linux
  # - don't have an R shared library
  - uses: r-lib/actions/setup-r-dependencies@v2-branch
    with:
      extra-packages: any::rcmdcheck
      needs: check
    env:
      R_KEEP_PKG_SOURCE: yes

  - uses: r-lib/actions/check-r-package@v2
    with:
      upload-snapshots: true
    env:
      R_KEEP_PKG_SOURCE: yes
