
name: R-hub

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'R-hub configutation.'
        type: string
        default: 'CRAN'

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      containers: ${{ steps.rhub-setup.outputs.containers }}
      platforms: ${{ steps.rhub-setup.outputs.platforms }}

    steps:
    # TODO: checkout is not needed, untimately, once we refer to repo explicitly
    - uses: actions/checkout@v3
    - uses: ./actions/rhub-setup
      with:
        config: ${{ github.event.inputs.config }}
      id: rhub-setup

  conts:
    needs: setup
    runs-on: ubuntu-latest
    name: ${{ matrix.config.name }}
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.setup.outputs.containers) }}
    container:
      image: ${{ matrix.config.container }}

    steps:
      - uses: actions/checkout@v3
      - uses: ./actions/rhub-check
        with:
          config: ${{ github.event.inputs.config }}

  notconts:
    needs: setup
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.setup.outputs.platforms) }}

    steps:
      - uses: actions/checkout@v3
      # TODO: user our own installer action for flexibility?
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
      - uses: ./actions/rhub-check
        with:
          config: ${{ github.event.inputs.config }}
