
name: R-hub

on:
  workflow_dispatch:

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      containers: ${{ steps.rhub-setup.outputs.containers }}
      platforms: ${{ steps.rhub-setup.outputs.platforms }}

    steps:
    - name: Setup R-hub platforms
      id: rhub-setup
      run: |
        containers='["ghcr.io/r-hub/containers/clang16:latest", "ghcr.io/r-hub/containers/gcc13:latest"]'
        echo "containers=$containers" >> $GITHUB_OUTPUT
        platforms='[{"os": "macos-latest","r": "release"},{"os":"windows-latest","r": "release"}]'
        echo "platforms=$platforms" >> $GITHUB_OUTPUT

  conts:
    needs: setup
    runs-on: ubuntu-latest
    name: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        container: ${{ fromJson(needs.setup.outputs.containers) }}
    container:
      image: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v3
      - name: R version
        run: |
          sessionInfo()
        shell: Rscript {0}

  notconts:
    needs: setup
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.setup.outputs.platforms) }}

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
      - name: R version
        run: |
          sessionInfo()
        shell: Rscript {0}
