
name: R-hub

on:
  workflow_dispatch:

jobs:

  conts:
    runs-on: ubuntu-latest
    name: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        container:
        - ghcr.io/r-hub/containers/clang16:latest
        - ghcr.io/r-hub/containers/gcc13:latest
    container:
      image: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v3
      - name: R version
        run: |
          sessionInfo()
        shell: Rscript {0}
      
  notconts:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: macOS-latest,   r: release }
          - { os: windows-latest, r: release }

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
      - name: R version
        run: |
          sessionInfo()
        shell: Rscript {0}
