
name: R-hub

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'A comma separated list of R-hub platforms to use.'
        type: string
        default: 'linux,windows,macos'

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      containers: ${{ steps.rhub-setup.outputs.containers }}
      platforms: ${{ steps.rhub-setup.outputs.platforms }}

    steps:
    - uses: actions/checkout@v3
    - uses: ./actions/rhub-setup
      with:
        config: ${{ github.event.inputs.config }}
      id: rhub-setup

  linux-containers:
    needs: setup
    runs-on: ubuntu-latest
    name: ${{ matrix.config.label }}
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.setup.outputs.containers) }}
    container:
      image: ${{ matrix.config.container }}

    steps:
      - uses: actions/checkout@v3
      - uses: ./actions/rhub-check
        with:
          config: ${{ github.event.inputs.config }}
          token: ${{ secrets.RHUB_TOKEN }}

  other-platforms:
    needs: setup
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.label }}
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.setup.outputs.platforms) }}

    steps:
      - uses: actions/checkout@v3
      - uses: ./actions/rhub-setup-r
        with:
          config: ${{ github.event.inputs.config }}
          platform: ${{ matrix.config.job-config }}
          token: ${{ secrets.RHUB_TOKEN }}
      - uses: ./actions/rhub-check
        with:
          config: ${{ matrix.config.job-config }}
          token: ${{ secrets.RHUB_TOKEN }}
